jobs:

- job:
  displayName: Conda package detection
  pool:
    vmImage: 'windows-latest'

  variables:
    EnableDetectorConda : True

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\bin"
    displayName: Add conda to PATH

