jobs:

- job:
  displayName: Conda package detection
  pool:
    vmImage: 'windows-latest'

  variables:
    EnableDetectorConda : True

  steps:
  - bash: echo "$PATH"
    displayName: Show Path

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - bash: echo "$PATH"
    displayName: Show Path  
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'


  

