name: canary-bootstrap
dependencies:
- python=3.8
- pip
- pip:
  - azureml-core==1.31.0
  - azure-ml-component==0.1.0.38576839
  - azureml-pipeline==1.31.0
  - pytest==6.2.4
  - shrike==1.8.0

  # Hints for pip's dependency resolver.
  # https://github.com/pypa/pip/issues/9187
  - azure-common==1.1.27
  - azure-core==1.17.0
  - azure-graphrbac==0.61.1
  - azure-mgmt-authorization==0.61.0
  - azure-mgmt-containerregistry==8.1.0
  - azure-mgmt-core==1.3.0
  - azure-mgmt-keyvault==9.0.0
  - azure-mgmt-resource==13.0.0
  - azure-mgmt-storage==11.2.0

  # https://o365exchange.visualstudio.com/O365%20Core/_git/MARS/pullrequest/1357172
  - --index-url https://o365exchange.pkgs.visualstudio.com/_packaging/PolymerPythonPackages/pypi/simple/
