# Compare:
# https://eemo.visualstudio.com/TEE/_git/TEEGit?path=%2FOffline%2FSmartCompose%2Fsrc%2Fpython%2Fsrc%2Fsteps%2Fprobe%2Fdefault_env.yaml&version=GBdevelop
name: probe
dependencies:
- python=3.7
- pip:
  - azureml-defaults==1.13.0
  - confidential-ml-utils==0.6.0
  - logging-tree==1.8.1
  - --index-url https://o365exchange.pkgs.visualstudio.com/_packaging/PolymerPythonPackages/pypi/simple/
