dependencies:
- python=3.7
- pip:
  - azureml-core==1.31.0
  - shrike==1.8.0
  - pandas==1.1.5
  - --index-url https://o365exchange.pkgs.visualstudio.com/_packaging/PolymerPythonPackages/pypi/simple/
